[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/somos-todos-um/igrejas/*"
  to = "/somos-todos-um/igrejas/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/somos-todos-um/igrejas"
  to = "/somos-todos-um/igrejas/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/somos-todos-um/*"
  to = "/somos-todos-um/:splat"
  status = 200

[[headers]]
  for = "/somos-todos-um/igrejas/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/somos-todos-um/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
