[build]
  publish = "."
  command = ""

# REGRA PARA O PORTAL JUR√çDICO
[[redirects]]
  from = "/direito"
  to = "/direito/juridico.html"
  status = 200
  force = true

[[redirects]]
  from = "/direito/*"
  to = "/direito/juridico.html"
  status = 200
  force = true

# REGRA PARA O SITE PRINCIPAL
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
