[build]
  publish = "."
  command = ""

# 1. Prioridade para o Jurídico
[[redirects]]
  from = "/direito/*"
  to = "/direito/index.html"
  status = 200
  force = true

# 2. Prioridade para o SIS-IG (se precisar)
[[redirects]]
  from = "/sis-ig/*"
  to = "/sis-ig/index.html"
  status = 200
  force = true

# 3. Regra para o site principal (Sempre por último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
