[build]
  publish = "."
  command = ""

# Regra para priorizar a pasta f√≠sica /direito
[[redirects]]
  from = "/direito/*"
  to = "/direito/:splat"
  status = 200

# Regra para o site principal (React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
