[build]
  publish = "dist"
  command = "npm run build"

# Regra 1: Para quando digitar bizmix.com.br/direito (sem barra)
[[redirects]]
  from = "/direito"
  to = "/direito/index.html"
  status = 200
  force = true

# Regra 2: Para quando digitar bizmix.com.br/direito/ (com barra ou subp√°ginas)
[[redirects]]
  from = "/direito/*"
  to = "/direito/index.html"
  status = 200
  force = true

# Regra 3: Para o site principal continuar funcionando
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
