[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/somos-todos-um/sis-ig"
  to = "/somos-todos-um/sis-ig/index.html"
  status = 200

[[redirects]]
  from = "/somos-todos-um/igrejas/*"
  to = "/somos-todos-um/sis-ig/"
  status = 301
  force = true

[[headers]]
  for = "/somos-todos-um/sis-ig/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/somos-todos-um/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
