[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/sis-ig"
  to = "/sis-ig/index.html"
  status = 200

[[redirects]]
  from = "/sis-ig/*"
  to = "/sis-ig/:splat"
  status = 200

[[redirects]]
  from = "/somos-todos-um/igrejas/*"
  to = "/sis-ig/"
  status = 301
  force = true

[[redirects]]
  from = "/somos-todos-um/sis-ig/*"
  to = "/sis-ig/"
  status = 301
  force = true

[[headers]]
  for = "/sis-ig/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/somos-todos-um/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
