[build]
  publish = "somos-todos-um"
  command = ""

# NÃ£o redirecionar /admin/ - deixar o Netlify servir os arquivos normalmente
[[redirects]]
  from = "/cadastro"
  to = "/cadastro/cadastro.html"
  status = 200
