[build]
  publish = "."
  command = ""

# 1. REGRA PARA O JURÍDICO (Prioridade Máxima)
[[redirects]]
  from = "/direito/*"
  to = "/direito/index.html"
  status = 200
  force = true

# 2. REGRA PARA O SIS-IG
[[redirects]]
  from = "/sis-ig/*"
  to = "/sis-ig/index.html"
  status = 200
  force = true

# 3. REGRA PARA O SOMOS TODOS UM
[[redirects]]
  from = "/somos-todos-um/*"
  to = "/somos-todos-um/index.html"
  status = 200
  force = true

# 4. REGRA PARA O SITE PRINCIPAL (Sempre por último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
